### ISSUE TITLE
Latest ansible-lint image causes CI breakage

### ISSUE THREAD

**Issue by kratsg** [cytopia/docker-ansible-lint#31]
Hi, I'm running this in a private GitLab project's CI, but here's what I see (it's been running just fine for a little over a year without issues nightly until last night):

```
Executing "step_script" stage of the job script
00:07
Using docker image sha256:ac519d2d1dce79826ecc5c6afda2ecb07048978eac8b1fd4f1a8bc50b6017f11 for cytopia/ansible-lint:latest with digest cytopia/ansible-lint@sha256:4c4f8165b8ee9f88f173fa1[23](https://gitlab.cern.ch/scipp/pixels/orchestration/-/jobs/25365080#L23)d85c108031d21e1074d0c76728aecf99ba8a401 ...
$ ansible-lint playbooks/*.yml
Traceback (most recent call last):
  File "/usr/bin/ansible-lint", line 8, in <module>
    sys.exit(_run_cli_entrypoint())
  File "/usr/lib/python3.10/site-packages/ansiblelint/__main__.py", line 314, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
  File "/usr/lib/python3.10/site-packages/ansiblelint/__main__.py", line 194, in main
    app = get_app(offline=options.offline)
  File "/usr/lib/python3.10/site-packages/ansiblelint/app.py", line 3[29](https://gitlab.cern.ch/scipp/pixels/orchestration/-/jobs/25365080#L29), in get_app
    app.runtime.prepare_environment(install_local=True, offline=offline)
  File "/usr/lib/python3.10/site-packages/ansible_compat/runtime.py", line [34](https://gitlab.cern.ch/scipp/pixels/orchestration/-/jobs/25365080#L34)0, in prepare_environment
    self.install_requirements(req_file, retry=retry)
  File "/usr/lib/python3.10/site-packages/ansible_compat/runtime.py", line 294, in install_requirements
    run = self.exec(cmd, retry=retry)
  File "/usr/lib/python3.10/site-packages/ansible_compat/runtime.py", line 150, in exec
    result = run_func(
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ansible-galaxy'
```

Any ideas how to fix this?

**Comment by cytopia** [comment]
@kratsg got it. This will fix it: https://github.com/cytopia/docker-ansible-lint/pull/32
